// tslint:disable:ordered-imports
import 'core-js/fn/array/filter';
import 'core-js/fn/array/map';
import 'core-js/fn/array/index-of';
import 'core-js/fn/array/is-array';
import 'core-js/fn/array/for-each';
import 'core-js/fn/date/now';
import 'performance-polyfill';
// tslint:enable:ordered-imports
